# Cloudflare Workers configuration
name = "pedi-psych-app"
main = "apps/app-api/src/index.ts"
compatibility_date = "2024-04-05" # Updated compatibility date

# Common environment variables
[vars]
REGION_DEFAULT = "India"
ADMIN_EMAIL = "satish@skids.health,hello@skids.health"

# Development environment
[env.dev]
name = "pedi-app-dev"
[env.dev.vars]
# WARNING: Temporary measure. Secrets should be managed via `wrangler secret` in a real environment.
JWT_SECRET = "dev-jwt-secret-2024-change-immediately"
[[env.dev.d1_databases]]
binding = "DB" # Standardized binding
database_name = "pedi_db_dev"
database_id = "ce6fd0f2-b6bf-40b1-a6be-e348d50c6266" # Assuming this is the dev DB ID

# Staging environment
[env.staging]
name = "pedi-app-staging"
[env.staging.vars]
ENVIRONMENT = "staging"
API_BASE_URL = "https://pedi-app-staging.devadmin-27f.workers.dev" # Placeholder URL
FRONTEND_URL = "https://staging.pedi-psych-kb-frontend.pages.dev" # Placeholder URL
# WARNING: Temporary measure. Secrets should be managed via `wrangler secret` in a real environment.
JWT_SECRET = "staging-jwt-secret-2024-change-immediately"
[[env.staging.d1_databases]]
binding = "DB" # Standardized binding
database_name = "pedi_db_staging"
database_id = "YOUR_STAGING_DB_ID_HERE" # Placeholder for staging DB

# Production environment
[env.production]
name = "pedi-app-prod"
[env.production.vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://pedi-psych-app.devadmin-27f.workers.dev"
FRONTEND_URL = "https://d29ad10a.pedi-psych-kb-frontend.pages.dev"
# WARNING: Temporary measure. Secrets should be managed via `wrangler secret` in a real environment.
JWT_SECRET = "prod-jwt-secret-2024-change-immediately"
[[env.production.d1_databases]]
binding = "DB" # Standardized binding
database_name = "pedi_db_prod"
database_id = "ce6fd0f2-b6bf-40b1-a6be-e348d50c6266" # Using the provided production DB ID
