name: Ops API Deploy and Smoke Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/ops-api/**'
      - 'packages/shared/**'
      - 'scripts/smoke-ops-api.sh'
      - 'scripts/seed-ops-api.sh'
      - 'scripts/data/**'
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd packages/shared && npm ci
          cd ../../apps/ops-api && npm ci

      - name: Build shared package
        run: |
          cd packages/shared
          npm run build

      - name: Run ops-api tests
        run: |
          npm run test -- -g "ops-api"

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Install dependencies
        run: |
          npm ci
          cd packages/shared && npm ci && npm run build
          cd ../../apps/ops-api && npm ci

      - name: Deploy to staging
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          # Deploy ops-api
          cd apps/ops-api
          wrangler deploy --name pedi-psych-ops-api-staging --env staging

      - name: Seed staging data
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          bash scripts/seed-ops-api.sh staging

      - name: Run smoke tests
        env:
          OPS_API_URL: https://pedi-psych-ops-api-staging.workers.dev
          CARD_ID: card-1
        run: |
          bash scripts/smoke-ops-api.sh $OPS_API_URL

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Install dependencies
        run: |
          npm ci
          cd packages/shared && npm ci && npm run build
          cd ../../apps/ops-api && npm ci

      - name: Deploy to production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          JWT_SECRET: ${{ secrets.OPS_API_JWT_SECRET }}
        run: |
          # Set production JWT secret
          cd apps/ops-api
          wrangler secret put JWT_SECRET --env production
          
          # Deploy ops-api
          wrangler deploy --name pedi-psych-ops-api --env production

      - name: Seed production data
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          bash scripts/seed-ops-api.sh production

      - name: Run smoke tests
        env:
          OPS_API_URL: https://pedi-psych-ops-api.workers.dev
          CARD_ID: card-1
        run: |
          bash scripts/smoke-ops-api.sh $OPS_API_URL